# Generated by Django 4.2.13 on 2024-05-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USERS',
            fields=[
                ('USER_ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('USER_PW', models.CharField(max_length=30)),
                ('USER_NM', models.CharField(max_length=50)),
                ('REG_DT', models.CharField(max_length=20)),
                ('REG_USER_ID', models.CharField(max_length=50)),
                ('REG_IP', models.CharField(max_length=20)),
                ('MOD_DT', models.CharField(max_length=50)),
                ('MOD_USER_ID', models.CharField(max_length=50)),
                ('MOD_IP', models.CharField(max_length=20)),
                ('USE_YN', models.CharField(max_length=2)),
                ('SNS_SIGN_ID', models.CharField(max_length=200)),
            ],
        ),
    ]
